package model;
import java.time.LocalDate;

/**
 * This class definition defines a job application. It consists of jopposting relevant information
 * like name of the jop position as well as information about the application for such a job post
 * e.g. application status.
 *
 */
public class JobApplication {

    /**
     * This enum class defines five states (Status) of an application. It is relevant for the property 'applicationStatus'
     * of the class 'jobApplication'.
     *
     * As it is a tiny class, experts recommend me to integrate in the large class 'JobApplication'. The model becomes more
     * compact then.
     */

    public enum Status {
        WaitingForReply,
        Invitation,
        Rejected,
        Offer,
        Withdrawn
    }

    //fields
    private int id =-1;
    private String postingName;
    private String company;
    private String postingLink;
    private LocalDate applicationDate;
    private String applicationStatus = convertStatusToString(Status.WaitingForReply);

    //new fields because of new columns
    private LocalDate nextInterviewDate;
    private String nextInterviewLink;
    private String nextInterviewPlace;
    private String contactPersonFullName;
    private String notes;

    /**
     * CONSTRUCTOR for creating an applied job entry
     * @param id: this is a unique id generated by MySQL, not here in the code. The id-value from MySQL is added by
     *         the code through the ArrayList 'appliedJobsList' in the Method 'DatabaseHandler.readDatabase()'
     * @param postingName: this is the name or title of the jobposting which has to be entered by the user when making
     *                   a database entry
     * @param company: this is the name of the company in the jobposting which has to be entered by the user when making
     *      *                   a database entry
     * @param postingLink: this is the link of the jobposting so that it can be retrieved  which has to be entered by the user when making
     *      *      *                   a database entry
     * @param applicationDate: this is the date of when the user had applied to the respective job  which has to be entered by the user when making
     *      *      *                   a database entry
     * @param applicationStatus: the applicationStatus is by default "WaitingForReply" because this is the first thing to happen
     *                         when just applied. Afterwards, the status can change between a predefined list of Status
     *                         which are defined in the enum class 'Status'
     *
     * NEW PARAMS need to be added with description
     *
     */
    public JobApplication(int id, String postingName, String company, String postingLink, LocalDate applicationDate, String applicationStatus){
        this.id = id;
        this.postingName=postingName;
        this.company=company;
        this.postingLink=postingLink;
        this.applicationDate= applicationDate;
        this.applicationStatus = applicationStatus;
    }

    //Constructor for new, larger table which had been introduced in 13.02.2026
    public JobApplication(int id, String postingName, String company, String postingLink, LocalDate applicationDate, String applicationStatus, LocalDate nextInterviewDate, String nextInterviewLink, String nextInterviewPlace, String contactPersonFullName, String notes) {
        this.id = id;
        this.postingName = postingName;
        this.company = company;
        this.postingLink = postingLink;
        this.applicationDate = applicationDate;
        this.applicationStatus = applicationStatus;
        this.nextInterviewDate = nextInterviewDate;
        this.nextInterviewLink = nextInterviewLink;
        this.nextInterviewPlace = nextInterviewPlace;
        this.contactPersonFullName = contactPersonFullName;
        this.notes = notes;
    }

    //Methods

    /**
     *
     * @param applicationStatusInList which is retrieved from the an entry of type 'JobApplication' in the list 'appliedJobsList'
     * @return the respective String to the applicationStatusInList which then can be accepted by the mySQL-database
     */

    public static String convertStatusToString(Status applicationStatusInList){
        if(applicationStatusInList.equals(Status.WaitingForReply)){
            return "Waiting for reply";
        }else if (applicationStatusInList.equals(Status.Invitation)) {
            return "Invitation";
        }else if (applicationStatusInList.equals(Status.Offer)){
            return "Offer";
        }else if(applicationStatusInList.equals(Status.Rejected)) {
            return "Rejected";
        }else {
            return "Withdrawn";
        }
    };

    /**
     *
     * @param applicationStatusInDatabase reads the application Status from the database which there is in String
     * @return the respective application Status of type 'Status' which can be saved in the 'appliedJobsList'
     */

    public static Status convertStringToStatus(String applicationStatusInDatabase){
        if(applicationStatusInDatabase.equals("Waiting for reply")){
            return Status.WaitingForReply;
        }else if (applicationStatusInDatabase.equals("Invitation")){
            return Status.Invitation;
        }else if (applicationStatusInDatabase.equals("Offer")){
            return Status.Offer;
        }else if(applicationStatusInDatabase.equals("Rejected")){
            return Status.Rejected;
        }else if (applicationStatusInDatabase.equals("Withdrawn")){
            return Status.Withdrawn;
        }else{
            System.out.println("The given String-Parameter does not correspond to a pre-defined application Status. ");
        }
        return null;
    }

    //Getters and Setters
    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getPostingName() {
        return postingName;
    }

    public void setPostingName(String postingName) {
        this.postingName = postingName;
    }

    public String getCompany() {
        return company;
    }

    public void setCompany(String company) {
        this.company = company;
    }

    public String getPostingLink() {
        return postingLink;
    }

    public void setPostingLinks(String postingLinks) {
        this.postingLink = postingLinks;
    }

    public LocalDate getApplicationDate() {
        return applicationDate;
    }

    public void setApplicationDate(LocalDate applicationDate) {
        this.applicationDate = applicationDate;
    }

    public String getApplicationStatus() {
        return applicationStatus;
    }

    public void setApplicationStatus(String applicationStatus) {
        this.applicationStatus = applicationStatus;
    }

    public void setPostingLink(String postingLink) {
        this.postingLink = postingLink;
    }

    public LocalDate getNextInterviewDate() {
        return nextInterviewDate;
    }

    public void setNextInterviewDate(LocalDate nextInterviewDate) {
        this.nextInterviewDate = nextInterviewDate;
    }

    public String getNextInterviewLink() {
        return nextInterviewLink;
    }

    public void setNextInterviewLink(String nextInterviewLink) {
        this.nextInterviewLink = nextInterviewLink;
    }

    public String getNextInterviewPlace() {
        return nextInterviewPlace;
    }

    public void setNextInterviewPlace(String nextInterviewPlace) {
        this.nextInterviewPlace = nextInterviewPlace;
    }

    public String getContactPersonFullName() {
        return contactPersonFullName;
    }

    public void setContactPersonFullName(String contactPersonFullName) {
        this.contactPersonFullName = contactPersonFullName;
    }

    public String getNotes() {
        return notes;
    }

    public void setNotes(String notes) {
        this.notes = notes;
    }
}
