-- This is the SQL-code for creating the SQL-database

-- MySQL Script generated by MySQL Workbench
-- Fri Jan 23 13:37:45 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema joblify-dashboard
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema joblify-dashboard
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `joblify-dashboard` DEFAULT CHARACTER SET utf8 ;
USE `joblify-dashboard` ;

-- -----------------------------------------------------
-- Table `joblify-dashboard`.`appliedJobsList`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `joblify-dashboard`.`appliedJobsList` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `postingName` VARCHAR(100) NOT NULL,
  `company` VARCHAR(100) NOT NULL,
  `postingLink` VARCHAR(500) NULL,
  `applicationDate` DATE NOT NULL,
  `applicationStatus` VARCHAR(45) NOT NULL,
  `appliedJobsListcol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
